tasks:
  - init: |
      # if a $TEAM is set, we "active" the team's VS Code Configuration by copying it to ws.code-workspace
      # We only build the select team's and the "shared" project
      # if no team is selected, we built all.

      if [ "$TEAM" == "a" ]; then
          ./shared/build.sh
          ./team-a/build.sh
      elif [ "$TEAM" == "b" ]; then
          ./shared/build.sh
          ./team-b/build.sh
      else
          ./shared/build.sh
          ./team-a/build.sh
          ./team-b/build.sh
      fi
    command: |
      if [ "$TEAM" == "a" ]; then
          code -a shared
          code -a team-a
      elif [ "$TEAM" == "b" ]; then
          code -a shared
          code -a team-a
      else
          code -a shared
          code -a team-a
          code -a team-b
      fi

